### ISSUE TITLE
springboot项目打包踩坑

### ISSUE THREAD

**Issue by Draymonders** [Draymonders/Code-Life#87]
打jar包的命令
- `mvn clean package -DskipTests=true`

然后新写的一个`Springboot`程序，需要打成jar包, 用的`spring-boot-maven-plugin`插件，遇到了`Jdk版本不对`和`No main class`的坑, 最终成功的打包`pom.xml`写法如下
```xml
<properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
</properties>

<build>
<plugins>
    <plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <version>2.1.7.RELEASE</version>
    <executions>
        <execution>
        <goals>
            <goal>repackage</goal>
        </goals>
        </execution>
    </executions>
    </plugin>
</plugins>
</build>
```

**Comment by Draymonders** [comment]
Dockerfile
```
FROM adoptopenjdk/openjdk11:alpine-slim

VOLUME /tmp

ENV TimeZone=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TimeZone /etc/localtime && echo $TimeZone > /etc/timezone

EXPOSE 2333

ENTRYPOINT ["java", "-jar", "/usr/share/redis-time-out/sturnus.jar"]

ARG JAR_FILE
ADD target/${JAR_FILE} /usr/share/redis-time-out/sturnus.jar
```

**Comment by Draymonders** [comment]
运行docker容器
```
docker run --name sturnus-redis-timeout --env REDIS_HOST="xx.xx.xx.xx" -d sturnus:latest
```

**Comment by Draymonders** [comment]
利用 https://github.com/Draymonders/docker-labs 构建基础环境。

**Comment by Draymonders** [comment]
将镜像持久化成文件，发送到server上
```
docker save sturnus > sturnus.tar
```

**Comment by Draymonders** [comment]
又踩到坑了，发现外网并不能访问服务

# expose
- `docker run` 有个`expose`,  `-p`，是映射宿主端口和容器端口，换句话说，就是将容器的对应端口服务公开给外界访问，而 `expose` 仅仅是声明容器打算使用什么端口而已，并不会自动在宿主进行端口映射。

# network_mode
// todo

**Comment by Draymonders** [comment]
最后确定的是
- `docker run -p 8080:8080` 出现外网无法访问的情况
- 最终选用的方案是 `docker-compose`去弄, `network_mode`无论是`bridge`还是`host`都可以
```yml
version: "3"

services:
  redis:
    image: redis
    restart: always
    ports:
      - 12300:6379

  sturnus-redis-app:
    image: sturnus
    ports:
      - 8080:8080
    container_name: sturnus-redis-app
    network_mode: host
    environment:
      - REDIS_HOST=10.40.86.81
      - REDIS_PORT=12300
    depends_on:
      - redis
```
